enum token{
    SPACE_TOKEN,
    DOT_TOKEN,
    COMMA_TOKEN,
    SEMICOLON_TOKEN,
    TAB_TOKEN,
    EOF_TOKEN, // end of line
    OPEN_BRACE_TOKEN,
    CLOSE_BRACE_TOKEN,
    OPEN_PARENTHESES_TOKEN,
    CLOSE_PARENTHESES_TOKEN,
    OPEN_BRACKETS_TOKEN,
    CLOSE_BRACKETS_TOKEN,
    PLUS_TOKEN,
    MINUS_TOKEN,
    MULTIPLY_TOKEN,
    DIVIDE_TOKEN,
    EQUAL_TOKEN,
    INT_TOKEN,
    CONST_TOKEN
};
